version: '3.1'
services:
  pg:
    container_name: your-crypto-postgres
    build: .
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ./:/var/lib/postgresql/data
    ports:
      - 5433:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  rmq:
    container_name: your-crypto-rmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - '15672:15672'
      - '5672:5672'
